
package attendanceservice.worktime;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WorkTime", targetNamespace = "http://WorkTime.AttendanceService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WorkTime {


    /**
     * 
     * @return
     *     returns java.util.List<attendanceservice.worktime.WorkTimeItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllWorkTime", targetNamespace = "http://WorkTime.AttendanceService/", className = "attendanceservice.worktime.GetAllWorkTime")
    @ResponseWrapper(localName = "getAllWorkTimeResponse", targetNamespace = "http://WorkTime.AttendanceService/", className = "attendanceservice.worktime.GetAllWorkTimeResponse")
    @Action(input = "http://WorkTime.AttendanceService/WorkTime/getAllWorkTimeRequest", output = "http://WorkTime.AttendanceService/WorkTime/getAllWorkTimeResponse")
    public List<WorkTimeItem> getAllWorkTime();

}
