
package attendanceservice.schedule;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ScheduleService", targetNamespace = "http://Schedule.AttendanceService/", wsdlLocation = "http://localhost:8080/ScheduleService?wsdl")
public class ScheduleService
    extends Service
{

    private final static URL SCHEDULESERVICE_WSDL_LOCATION;
    private final static WebServiceException SCHEDULESERVICE_EXCEPTION;
    private final static QName SCHEDULESERVICE_QNAME = new QName("http://Schedule.AttendanceService/", "ScheduleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ScheduleService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCHEDULESERVICE_WSDL_LOCATION = url;
        SCHEDULESERVICE_EXCEPTION = e;
    }

    public ScheduleService() {
        super(__getWsdlLocation(), SCHEDULESERVICE_QNAME);
    }

    public ScheduleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SCHEDULESERVICE_QNAME, features);
    }

    public ScheduleService(URL wsdlLocation) {
        super(wsdlLocation, SCHEDULESERVICE_QNAME);
    }

    public ScheduleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SCHEDULESERVICE_QNAME, features);
    }

    public ScheduleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScheduleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Schedule
     */
    @WebEndpoint(name = "SchedulePort")
    public Schedule getSchedulePort() {
        return super.getPort(new QName("http://Schedule.AttendanceService/", "SchedulePort"), Schedule.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Schedule
     */
    @WebEndpoint(name = "SchedulePort")
    public Schedule getSchedulePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Schedule.AttendanceService/", "SchedulePort"), Schedule.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCHEDULESERVICE_EXCEPTION!= null) {
            throw SCHEDULESERVICE_EXCEPTION;
        }
        return SCHEDULESERVICE_WSDL_LOCATION;
    }

}
