
package erpservice.resource;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResourceService", targetNamespace = "http://Resource.ERPService/", wsdlLocation = "http://localhost:8080/resourceService?wsdl")
public class ResourceService
    extends Service
{

    private final static URL RESOURCESERVICE_WSDL_LOCATION;
    private final static WebServiceException RESOURCESERVICE_EXCEPTION;
    private final static QName RESOURCESERVICE_QNAME = new QName("http://Resource.ERPService/", "ResourceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/resourceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESOURCESERVICE_WSDL_LOCATION = url;
        RESOURCESERVICE_EXCEPTION = e;
    }

    public ResourceService() {
        super(__getWsdlLocation(), RESOURCESERVICE_QNAME);
    }

    public ResourceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESOURCESERVICE_QNAME, features);
    }

    public ResourceService(URL wsdlLocation) {
        super(wsdlLocation, RESOURCESERVICE_QNAME);
    }

    public ResourceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESOURCESERVICE_QNAME, features);
    }

    public ResourceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResourceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Resource
     */
    @WebEndpoint(name = "ResourcePort")
    public Resource getResourcePort() {
        return super.getPort(new QName("http://Resource.ERPService/", "ResourcePort"), Resource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Resource
     */
    @WebEndpoint(name = "ResourcePort")
    public Resource getResourcePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Resource.ERPService/", "ResourcePort"), Resource.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESOURCESERVICE_EXCEPTION!= null) {
            throw RESOURCESERVICE_EXCEPTION;
        }
        return RESOURCESERVICE_WSDL_LOCATION;
    }

}
