
package orderservice.order;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Order", targetNamespace = "http://Order.OrderService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Order {


    /**
     * 
     * @return
     *     returns java.util.List<orderservice.order.OrderItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://Order.OrderService/", className = "orderservice.order.GetAllOrders")
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://Order.OrderService/", className = "orderservice.order.GetAllOrdersResponse")
    @Action(input = "http://Order.OrderService/Order/getAllOrdersRequest", output = "http://Order.OrderService/Order/getAllOrdersResponse")
    public List<OrderItem> getAllOrders();

}
