
package erpservice.bom;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BOM", targetNamespace = "http://BOM.ERPService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BOM {


    /**
     * 
     * @return
     *     returns java.util.List<erpservice.bom.BomItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBOM", targetNamespace = "http://BOM.ERPService/", className = "erpservice.bom.GetAllBOM")
    @ResponseWrapper(localName = "getAllBOMResponse", targetNamespace = "http://BOM.ERPService/", className = "erpservice.bom.GetAllBOMResponse")
    @Action(input = "http://BOM.ERPService/BOM/getAllBOMRequest", output = "http://BOM.ERPService/BOM/getAllBOMResponse")
    public List<BomItem> getAllBOM();

}
