
package erpservice.bom;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BOMService", targetNamespace = "http://BOM.ERPService/", wsdlLocation = "http://localhost:8080/BOMService?wsdl")
public class BOMService
    extends Service
{

    private final static URL BOMSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOMSERVICE_EXCEPTION;
    private final static QName BOMSERVICE_QNAME = new QName("http://BOM.ERPService/", "BOMService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BOMService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOMSERVICE_WSDL_LOCATION = url;
        BOMSERVICE_EXCEPTION = e;
    }

    public BOMService() {
        super(__getWsdlLocation(), BOMSERVICE_QNAME);
    }

    public BOMService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOMSERVICE_QNAME, features);
    }

    public BOMService(URL wsdlLocation) {
        super(wsdlLocation, BOMSERVICE_QNAME);
    }

    public BOMService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOMSERVICE_QNAME, features);
    }

    public BOMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BOMService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BOM
     */
    @WebEndpoint(name = "BOMPort")
    public BOM getBOMPort() {
        return super.getPort(new QName("http://BOM.ERPService/", "BOMPort"), BOM.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BOM
     */
    @WebEndpoint(name = "BOMPort")
    public BOM getBOMPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://BOM.ERPService/", "BOMPort"), BOM.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOMSERVICE_EXCEPTION!= null) {
            throw BOMSERVICE_EXCEPTION;
        }
        return BOMSERVICE_WSDL_LOCATION;
    }

}
