
package erpservice.goods;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GoodsService", targetNamespace = "http://Goods.ERPService/", wsdlLocation = "http://localhost:8080/goodsService?wsdl")
public class GoodsService
    extends Service
{

    private final static URL GOODSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GOODSSERVICE_EXCEPTION;
    private final static QName GOODSSERVICE_QNAME = new QName("http://Goods.ERPService/", "GoodsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/goodsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GOODSSERVICE_WSDL_LOCATION = url;
        GOODSSERVICE_EXCEPTION = e;
    }

    public GoodsService() {
        super(__getWsdlLocation(), GOODSSERVICE_QNAME);
    }

    public GoodsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GOODSSERVICE_QNAME, features);
    }

    public GoodsService(URL wsdlLocation) {
        super(wsdlLocation, GOODSSERVICE_QNAME);
    }

    public GoodsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GOODSSERVICE_QNAME, features);
    }

    public GoodsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GoodsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Goods
     */
    @WebEndpoint(name = "GoodsPort")
    public Goods getGoodsPort() {
        return super.getPort(new QName("http://Goods.ERPService/", "GoodsPort"), Goods.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Goods
     */
    @WebEndpoint(name = "GoodsPort")
    public Goods getGoodsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Goods.ERPService/", "GoodsPort"), Goods.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GOODSSERVICE_EXCEPTION!= null) {
            throw GOODSSERVICE_EXCEPTION;
        }
        return GOODSSERVICE_WSDL_LOCATION;
    }

}
