
package staffservice.staff;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StaffService", targetNamespace = "http://Staff.StaffService/", wsdlLocation = "http://localhost:8080/StaffService?wsdl")
public class StaffService
    extends Service
{

    private final static URL STAFFSERVICE_WSDL_LOCATION;
    private final static WebServiceException STAFFSERVICE_EXCEPTION;
    private final static QName STAFFSERVICE_QNAME = new QName("http://Staff.StaffService/", "StaffService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/StaffService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STAFFSERVICE_WSDL_LOCATION = url;
        STAFFSERVICE_EXCEPTION = e;
    }

    public StaffService() {
        super(__getWsdlLocation(), STAFFSERVICE_QNAME);
    }

    public StaffService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STAFFSERVICE_QNAME, features);
    }

    public StaffService(URL wsdlLocation) {
        super(wsdlLocation, STAFFSERVICE_QNAME);
    }

    public StaffService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STAFFSERVICE_QNAME, features);
    }

    public StaffService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StaffService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Staff
     */
    @WebEndpoint(name = "StaffPort")
    public Staff getStaffPort() {
        return super.getPort(new QName("http://Staff.StaffService/", "StaffPort"), Staff.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Staff
     */
    @WebEndpoint(name = "StaffPort")
    public Staff getStaffPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Staff.StaffService/", "StaffPort"), Staff.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STAFFSERVICE_EXCEPTION!= null) {
            throw STAFFSERVICE_EXCEPTION;
        }
        return STAFFSERVICE_WSDL_LOCATION;
    }

}
