
package com.proto.service.client.staff;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Staff", targetNamespace = "http://Staff.StaffService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Staff {


    /**
     * 
     * @param arg0
     * @return
     *     returns staffservice.staff.StaffIItem
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStaffByUsername", targetNamespace = "http://Staff.StaffService/", className = "staffservice.staff.GetStaffByUsername")
    @ResponseWrapper(localName = "getStaffByUsernameResponse", targetNamespace = "http://Staff.StaffService/", className = "staffservice.staff.GetStaffByUsernameResponse")
    @Action(input = "http://Staff.StaffService/Staff/getStaffByUsernameRequest", output = "http://Staff.StaffService/Staff/getStaffByUsernameResponse")
    public StaffIItem getStaffByUsername(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     *
     * @return
     *     returns java.util.List<staffservice.staff.StaffIItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllStaff", targetNamespace = "http://Staff.StaffService/", className = "staffservice.staff.GetAllStaff")
    @ResponseWrapper(localName = "getAllStaffResponse", targetNamespace = "http://Staff.StaffService/", className = "staffservice.staff.GetAllStaffResponse")
    @Action(input = "http://Staff.StaffService/Staff/getAllStaffRequest", output = "http://Staff.StaffService/Staff/getAllStaffResponse")
    public List<StaffIItem> getAllStaff();

    /**
     *
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "Verify")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Verify", targetNamespace = "http://Staff.StaffService/", className = "staffservice.staff.Verify")
    @ResponseWrapper(localName = "VerifyResponse", targetNamespace = "http://Staff.StaffService/", className = "staffservice.staff.VerifyResponse")
    @Action(input = "http://Staff.StaffService/Staff/VerifyRequest", output = "http://Staff.StaffService/Staff/VerifyResponse")
    public boolean verify(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
