
package com.proto.service.client.attendanceservice.worktime;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WorkTimeService", targetNamespace = "http://WorkTime.AttendanceService/", wsdlLocation = "http://localhost:8080/WorkTimeService?wsdl")
public class WorkTimeService
    extends Service
{

    private final static URL WORKTIMESERVICE_WSDL_LOCATION;
    private final static WebServiceException WORKTIMESERVICE_EXCEPTION;
    private final static QName WORKTIMESERVICE_QNAME = new QName("http://WorkTime.AttendanceService/", "WorkTimeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WorkTimeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WORKTIMESERVICE_WSDL_LOCATION = url;
        WORKTIMESERVICE_EXCEPTION = e;
    }

    public WorkTimeService() {
        super(__getWsdlLocation(), WORKTIMESERVICE_QNAME);
    }

    public WorkTimeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WORKTIMESERVICE_QNAME, features);
    }

    public WorkTimeService(URL wsdlLocation) {
        super(wsdlLocation, WORKTIMESERVICE_QNAME);
    }

    public WorkTimeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WORKTIMESERVICE_QNAME, features);
    }

    public WorkTimeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkTimeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WorkTime
     */
    @WebEndpoint(name = "WorkTimePort")
    public WorkTime getWorkTimePort() {
        return super.getPort(new QName("http://WorkTime.AttendanceService/", "WorkTimePort"), WorkTime.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkTime
     */
    @WebEndpoint(name = "WorkTimePort")
    public WorkTime getWorkTimePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WorkTime.AttendanceService/", "WorkTimePort"), WorkTime.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WORKTIMESERVICE_EXCEPTION!= null) {
            throw WORKTIMESERVICE_EXCEPTION;
        }
        return WORKTIMESERVICE_WSDL_LOCATION;
    }

}
